### PR TITLE
Updates on the website 

### PR DESCRIPTION
**Pull request by Brightlaz**
- Updated the home page
- Created and added the mobile version of the animation of the home page hero
- Updated the contact page

### CODE REVIEW

**Comment by code-space-nigeria** [comment]
Hey @Brightlaz  the green card on the home page is hidden

**Comment by Brightlaz** [comment]
> Hey @Brightlaz the green card on the home page is hidden

fixing it now sir, when i make the commit then you can merge

**Comment by Brightlaz** [comment]
> Hey @Brightlaz the green card on the home page is hidden

@code-space-nigeria I have adjusted the position it's no more hidden now

**Comment by code-space-nigeria** [comment]
Hey @Brightlaz  a liitle adjustment to the hero section in the contact page to fit all screen like others 
image

**Pull request merged**
